BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS access_key (
	access_key_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	access_key_desc VARCHAR(200) NOT NULL, 
	access_token TEXT NOT NULL, 
	expires_at DATETIME, 
	active BOOLEAN, 
	for_user_id INTEGER, 
	user_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(for_user_id) REFERENCES users (user_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id)
);
CREATE TABLE IF NOT EXISTS app (
	app_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	app VARCHAR(20) NOT NULL, 
	app_desc TEXT, 
	version VARCHAR(10) NOT NULL, 
	email VARCHAR(200), 
	db VARCHAR(200) NOT NULL, 
	attach_logo VARCHAR(200), 
	config TEXT, 
	user_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	UNIQUE (app), 
	FOREIGN KEY(user_id) REFERENCES users (user_id)
);
CREATE TABLE IF NOT EXISTS "arrow_flight" (
	"arrow_flight_id"	INTEGER NOT NULL,
	"arrow_flight"	VARCHAR(200) NOT NULL,
	"arrow_flight_desc"	TEXT,
	"startup_sql"	TEXT,
	"main_sql"	TEXT NOT NULL,
	"shutdown_sql"	TEXT,
	"active"	BOOLEAN,
	"user_id"	INTEGER,
	"app_id"	INTEGER,
	"created_at"	DATETIME,
	"updated_at"	DATETIME,
	"excluded"	BOOLEAN,
	"flight_schema"	TEXT,
	"table_discover_sql"	TEXT,
	"table_scan_tmpl_sql"	TEXT, arrow_flight_conf text null,
	UNIQUE("arrow_flight"),
	PRIMARY KEY("arrow_flight_id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS arrow_flight_table (
	arrow_flight_table_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	arrow_flight_table VARCHAR(200) NOT NULL, 
	arrow_flight_table_desc TEXT, 
	arrow_flight_id INTEGER, 
	active BOOLEAN, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	UNIQUE (arrow_flight_table), 
	FOREIGN KEY(arrow_flight_id) REFERENCES arrow_flight (arrow_flight_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS arrow_flight_table_field (
	arrow_flight_table_field_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	arrow_flight_table_field VARCHAR(200) NOT NULL, 
	arrow_flight_table_field_desc TEXT, 
	arrow_flight_table_id INTEGER, 
	arrow_flight_id INTEGER, 
	active BOOLEAN, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	UNIQUE (arrow_flight_table_field), 
	FOREIGN KEY(arrow_flight_table_id) REFERENCES arrow_flight_table (arrow_flight_table_id), 
	FOREIGN KEY(arrow_flight_id) REFERENCES arrow_flight (arrow_flight_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS arrow_flight_table_scope (
	arrow_flight_table_scope_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	arrow_flight_table_scope VARCHAR(200) NOT NULL, 
	arrow_flight_table_scope_desc TEXT, 
	arrow_flight_table_scope_sql TEXT NOT NULL, 
	arrow_flight_table_id INTEGER, 
	arrow_flight_id INTEGER, 
	active BOOLEAN, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	UNIQUE (arrow_flight_table_scope), 
	FOREIGN KEY(arrow_flight_table_id) REFERENCES arrow_flight_table (arrow_flight_table_id), 
	FOREIGN KEY(arrow_flight_id) REFERENCES arrow_flight (arrow_flight_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS calendar (
	calendar_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	calendar VARCHAR(100) NOT NULL, 
	calendar_desc TEXT, 
	calendar_email VARCHAR(200), 
	calendar_color VARCHAR(50), 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS column_level_access (
	column_level_access_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	"column" INTEGER NOT NULL, 
	table_id INTEGER, 
	"table" VARCHAR(200) NOT NULL, 
	db VARCHAR(200) NOT NULL, 
	user_id INTEGER, 
	app_id INTEGER, 
	"create" BOOLEAN, 
	read BOOLEAN, 
	"update" BOOLEAN, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(table_id) REFERENCES "table" (table_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS cron (
	cron_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	cron VARCHAR(50) NOT NULL, 
	cron_desc VARCHAR(200) NOT NULL, 
	api VARCHAR(200) NOT NULL, 
	app_id INTEGER, 
	db VARCHAR(200), 
	"table" VARCHAR(50), 
	active BOOLEAN, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS cron_log (
	cron_log_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	cron_id INTEGER, 
	cron VARCHAR(50) NOT NULL, 
	cron_desc VARCHAR(200) NOT NULL, 
	api VARCHAR(200) NOT NULL, 
	start_at DATETIME, 
	end_at DATETIME, 
	success BOOLEAN, 
	cron_msg TEXT NOT NULL, 
	app_id INTEGER, 
	db VARCHAR(200), 
	"table" VARCHAR(50), 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(cron_id) REFERENCES cron (cron_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS custom_form (
	custom_form_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	"table" VARCHAR(200), 
	db VARCHAR(200), 
	config TEXT, 
	app_id INTEGER, 
	user_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(app_id) REFERENCES app (app_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id)
);
CREATE TABLE IF NOT EXISTS custom_table (
	custom_table_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	"table" VARCHAR(200), 
	db VARCHAR(200), 
	config TEXT, 
	app_id INTEGER, 
	user_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(app_id) REFERENCES app (app_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id)
);
CREATE TABLE IF NOT EXISTS dashboard (
	dashboard_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	dashboard VARCHAR(200), 
	dashboard_desc TEXT, 
	dashboard_conf TEXT NOT NULL, 
	"order" INTEGER, 
	active BOOLEAN, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS dashboard_comment (
	dashboard_comment_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	dashboard_comment TEXT, 
	dashboard VARCHAR(200), 
	active BOOLEAN, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS env (
	env_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	env_name VARCHAR(200) NOT NULL, 
	env_value TEXT NOT NULL, 
	active BOOLEAN, 
	user_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, on_srv_start boolean null, 
	UNIQUE (env_name), 
	FOREIGN KEY(user_id) REFERENCES users (user_id)
);
CREATE TABLE IF NOT EXISTS etl_rb_exp_dtail (
	etl_rb_exp_dtail_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	etl_rb_exp_dtail VARCHAR(200) NOT NULL, 
	etl_rb_exp_dtail_desc TEXT, 
	etl_rbase_export_id INTEGER NOT NULL, 
	etl_report_base_id INTEGER NOT NULL, 
	sql_export_query TEXT, 
	"database" VARCHAR(200) NOT NULL, 
	dest_sheet_name VARCHAR(200), 
	dest_table_name VARCHAR(200), 
	etl_rb_exp_dtail_conf TEXT, 
	active BOOLEAN, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(etl_rbase_export_id) REFERENCES etl_rbase_export (etl_rbase_export_id), 
	FOREIGN KEY(etl_report_base_id) REFERENCES etl_report_base (etl_report_base_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS etl_rb_output_field (
	etl_rb_output_field_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	etl_rb_output_field VARCHAR(200) NOT NULL, 
	etl_rb_output_field_desc TEXT, 
	etl_rbase_output_id INTEGER NOT NULL, 
	sql_select TEXT NOT NULL, 
	sql_from TEXT, 
	sql_join TEXT, 
	sql_where TEXT, 
	sql_group_by TEXT, 
	sql_order_by TEXT, 
	sql_window TEXT, 
	sql_having TEXT, 
	field_order INTEGER, 
	fields_used TEXT, 
	etl_report_base_id INTEGER, 
	active BOOLEAN, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(etl_rbase_output_id) REFERENCES etl_rbase_output (etl_rbase_output_id), 
	FOREIGN KEY(etl_report_base_id) REFERENCES etl_report_base (etl_report_base_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS etl_rb_reconc_dtail (
	etl_rb_reconc_dtail_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	etl_rb_reconc_dtail VARCHAR(50) NOT NULL, 
	etl_rb_reconc_dtail_desc VARCHAR(200) NOT NULL, 
	sql_query_val_1 TEXT, 
	sql_query_val_2 TEXT, 
	is_eval_formula BOOLEAN, 
	sql_reconcilia_query TEXT, 
	comments TEXT, 
	etl_rb_reconcilia_id INTEGER NOT NULL, 
	etl_report_base_id INTEGER, 
	active BOOLEAN, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(etl_rb_reconcilia_id) REFERENCES etl_rb_reconcilia (etl_rb_reconcilia_id), 
	FOREIGN KEY(etl_report_base_id) REFERENCES etl_report_base (etl_report_base_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS etl_rb_reconcilia (
	etl_rb_reconcilia_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	etl_rb_reconcilia VARCHAR(200) NOT NULL, 
	etl_rb_reconcilia_desc TEXT, 
	etl_rb_reconc_template TEXT, 
	"database" VARCHAR(200) NOT NULL, 
	active BOOLEAN, 
	etl_report_base_id INTEGER NOT NULL, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(etl_report_base_id) REFERENCES etl_report_base (etl_report_base_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS etl_rbase_backup (
	backup_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	backup VARCHAR(200) NOT NULL, 
	backup_sql TEXT, 
	backup_copy_to BOOLEAN, 
	backup_copy_path VARCHAR(200), 
	backup_conf TEXT, 
	active BOOLEAN, 
	etl_report_base_id INTEGER, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(etl_report_base_id) REFERENCES etl_report_base (etl_report_base_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS etl_rbase_export (
	etl_rbase_export_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	etl_rbase_export VARCHAR(200) NOT NULL, 
	etl_rbase_export_desc TEXT, 
	etl_report_base_id INTEGER NOT NULL, 
	export_type_id INTEGER NOT NULL, 
	attach_file_template VARCHAR(200) NOT NULL, 
	txt_fix_format_layout TEXT, 
	txt_fix_format_header TEXT, 
	etl_rbase_export_conf TEXT, 
	etl_rbase_output_id INTEGER, 
	"database" VARCHAR(200) NOT NULL, 
	active BOOLEAN, 
	"ignore" BOOLEAN, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(etl_report_base_id) REFERENCES etl_report_base (etl_report_base_id), 
	FOREIGN KEY(export_type_id) REFERENCES export_type (export_type_id), 
	FOREIGN KEY(etl_rbase_output_id) REFERENCES etl_rbase_output (etl_rbase_output_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS etl_rbase_input (
	etl_rbase_input_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	etl_rbase_input VARCHAR(200) NOT NULL, 
	etl_rbase_input_desc TEXT, 
	etl_report_base_id INTEGER NOT NULL, 
	input_type_id INTEGER, 
	save_only_temp BOOLEAN, 
	replace_existing_data BOOLEAN, 
	check_ref_date BOOLEAN, 
	ref_date_field VARCHAR(200), 
	date_format_org VARCHAR(200), 
	other_date_fields VARCHAR(200), 
	ref_id_keys VARCHAR(200), 
	last_update_date_field VARCHAR(200), 
	incremental_extract BOOLEAN, 
	destination_table VARCHAR(200) NOT NULL, 
	"database" VARCHAR(200) NOT NULL, 
	allow_import BOOLEAN, 
	multiple_sheets BOOLEAN, 
	specific_sheets VARCHAR(200), 
	specific_range VARCHAR(200), 
	columns_to_import VARCHAR(200), 
	txt_fix_format_layout VARCHAR(200), 
	headers VARCHAR(200), 
	spreadsheet_forms BOOLEAN, 
	spreadsheet_forms_map VARCHAR(200), 
	etl_rbase_input_conf TEXT, 
	active BOOLEAN, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(etl_report_base_id) REFERENCES etl_report_base (etl_report_base_id), 
	FOREIGN KEY(input_type_id) REFERENCES input_type (input_type_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS etl_rbase_notify (
	notify_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	notify_subject VARCHAR(200) NOT NULL, 
	notify_body TEXT NOT NULL, 
	notify_to VARCHAR(200) NOT NULL, 
	notify_cc VARCHAR(200), 
	notify_attach_exports BOOLEAN, 
	notify_copy_exports_to BOOLEAN, 
	notify_copy_exports_path VARCHAR(200), 
	notify_conf TEXT, 
	send_email BOOLEAN, 
	active BOOLEAN, 
	etl_report_base_id INTEGER, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(etl_report_base_id) REFERENCES etl_report_base (etl_report_base_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS etl_rbase_output (
	etl_rbase_output_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	etl_rbase_output VARCHAR(200) NOT NULL, 
	etl_rbase_output_desc TEXT, 
	etl_report_base_id INTEGER NOT NULL, 
	output_type_id INTEGER, 
	date_field VARCHAR(200), 
	date_field_format VARCHAR(200), 
	destination_table VARCHAR(200) NOT NULL, 
	"database" VARCHAR(200) NOT NULL, 
	append_it BOOLEAN, 
	output_order INTEGER, 
	etl_rbase_output_conf TEXT, 
	active BOOLEAN, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(etl_report_base_id) REFERENCES etl_report_base (etl_report_base_id), 
	FOREIGN KEY(output_type_id) REFERENCES output_type (output_type_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS etl_rbase_quality (
	etl_rbase_quality_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	etl_rbase_quality VARCHAR(200) NOT NULL, 
	etl_rbase_quality_desc TEXT, 
	etl_report_base_id INTEGER NOT NULL, 
	sql_quality_check TEXT NOT NULL, 
	sql_quality_fix TEXT, 
	comments TEXT, 
	fields TEXT, 
	tables TEXT, 
	"database" VARCHAR(200) NOT NULL, 
	etl_rbase_quality_conf TEXT, 
	active BOOLEAN, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(etl_report_base_id) REFERENCES etl_report_base (etl_report_base_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS etl_rbase_script (
	script_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	script VARCHAR(200) NOT NULL, 
	script_sql TEXT, 
	script_conf TEXT, 
	active BOOLEAN, 
	etl_report_base_id INTEGER, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(etl_report_base_id) REFERENCES etl_report_base (etl_report_base_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS etl_report_base (
	etl_report_base_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	etl_report_base VARCHAR(200) NOT NULL, 
	etl_report_base_desc TEXT, 
	attach_etl_rbase_doc VARCHAR(200), 
	periodicity_id INTEGER, 
	"database" VARCHAR(200) NOT NULL, 
	includes_output BOOLEAN, 
	includes_data_quality BOOLEAN, 
	includes_data_reconci BOOLEAN, 
	includes_exports BOOLEAN, 
	includes_backup BOOLEAN, 
	includes_script BOOLEAN, 
	includes_notify BOOLEAN, 
	etl_report_base_conf TEXT, 
	active BOOLEAN, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	UNIQUE (etl_report_base), 
	FOREIGN KEY(periodicity_id) REFERENCES periodicity (periodicity_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS etl_report_base_log (
	log_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	type VARCHAR(50) NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	ref DATE, 
	start DATETIME, 
	"end" DATETIME, 
	timer VARCHAR(10), 
	success BOOLEAN, 
	msg TEXT, 
	num_rows INTEGER, 
	errors INTEGER, 
	fixes INTEGER, 
	fname VARCHAR(200), 
	html TEXT, 
	etl_report_base_id INTEGER, 
	app_id INTEGER, 
	user_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(etl_report_base_id) REFERENCES etl_report_base (etl_report_base_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id)
);
CREATE TABLE IF NOT EXISTS export_type (
	export_type_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	export_type VARCHAR(100) NOT NULL, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	UNIQUE (export_type)
);
CREATE TABLE IF NOT EXISTS input_type (
	input_type_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	input_type VARCHAR(100) NOT NULL, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	UNIQUE (input_type)
);
CREATE TABLE IF NOT EXISTS lang (
	lang_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	lang VARCHAR(4) NOT NULL, 
	lang_desc VARCHAR(200), 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	UNIQUE (lang)
);
CREATE TABLE IF NOT EXISTS manage_query (
	manage_query_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	manage_query VARCHAR(200) NOT NULL, 
	"database" VARCHAR(200) NOT NULL, 
	manage_query_conf TEXT, 
	active BOOLEAN, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS menu (
	menu_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	menu VARCHAR(200) NOT NULL, 
	menu_desc TEXT, 
	menu_icon VARCHAR(20), 
	menu_order INTEGER, 
	menu_config TEXT, 
	app_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	active BOOLEAN, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(app_id) REFERENCES app (app_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id)
);
CREATE TABLE IF NOT EXISTS menu_table (
	menu_table_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	menu_id INTEGER, 
	table_id INTEGER, 
	app_id INTEGER, 
	user_id INTEGER, 
	active BOOLEAN, 
	requires_rla BOOLEAN, 
	menu_table_cnf TEXT, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(menu_id) REFERENCES menu (menu_id), 
	FOREIGN KEY(table_id) REFERENCES "table" (table_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id)
);
CREATE TABLE IF NOT EXISTS output_type (
	output_type_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	output_type VARCHAR(100) NOT NULL, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	UNIQUE (output_type)
);
CREATE TABLE IF NOT EXISTS periodicity (
	periodicity_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	periodicity VARCHAR(100) NOT NULL, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	UNIQUE (periodicity)
);
CREATE TABLE IF NOT EXISTS repeat_type (
	repeat_type_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	repeat_type VARCHAR(10) NOT NULL, 
	excluded BOOLEAN
);
CREATE TABLE IF NOT EXISTS role (
	role_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	role VARCHAR(20) NOT NULL, 
	role_desc TEXT, 
	config TEXT, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	UNIQUE (role)
);
CREATE TABLE IF NOT EXISTS role_app (
	role_app_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	role_id INTEGER, 
	app_id INTEGER, 
	access BOOLEAN, 
	user_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(role_id) REFERENCES role (role_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id)
);
CREATE TABLE IF NOT EXISTS role_app_menu (
	role_app_menu_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	role_id INTEGER, 
	app_id INTEGER, 
	menu_id INTEGER, 
	access BOOLEAN, 
	user_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(role_id) REFERENCES role (role_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id), 
	FOREIGN KEY(menu_id) REFERENCES menu (menu_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id)
);
CREATE TABLE IF NOT EXISTS role_app_menu_table (
	role_app_menu_table_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	role_id INTEGER, 
	app_id INTEGER, 
	menu_id INTEGER, 
	table_id INTEGER, 
	"create" BOOLEAN, 
	read BOOLEAN, 
	"update" BOOLEAN, 
	"delete" BOOLEAN, 
	user_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(role_id) REFERENCES role (role_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id), 
	FOREIGN KEY(menu_id) REFERENCES menu (menu_id), 
	FOREIGN KEY(table_id) REFERENCES "table" (table_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id)
);
CREATE TABLE IF NOT EXISTS role_row_level_access (
	role_row_level_access_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	role_id INTEGER, 
	row_id INTEGER NOT NULL, 
	table_id INTEGER, 
	"table" VARCHAR(200) NOT NULL, 
	db VARCHAR(200) NOT NULL, 
	user_id INTEGER, 
	app_id INTEGER, 
	read BOOLEAN, 
	"update" BOOLEAN, 
	"delete" BOOLEAN, 
	share BOOLEAN, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(role_id) REFERENCES role (role_id), 
	FOREIGN KEY(table_id) REFERENCES "table" (table_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS row_level_access (
	row_level_access_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	row_id INTEGER NOT NULL, 
	table_id INTEGER, 
	"table" VARCHAR(200) NOT NULL, 
	db VARCHAR(200) NOT NULL, 
	user_id INTEGER, 
	app_id INTEGER, 
	read BOOLEAN, 
	"update" BOOLEAN, 
	"delete" BOOLEAN, 
	share BOOLEAN, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(table_id) REFERENCES "table" (table_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS source_type (
	source_type_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	source_type VARCHAR(100) NOT NULL, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	UNIQUE (source_type)
);
CREATE TABLE IF NOT EXISTS "table" (
	table_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	"table" VARCHAR(50) NOT NULL, 
	table_desc VARCHAR(200), 
	db VARCHAR(50), 
	requires_rla BOOLEAN, 
	user_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(user_id) REFERENCES users (user_id)
);
CREATE TABLE IF NOT EXISTS "table_schema" (
	"table_schema_id"	INTEGER NOT NULL,
	"db"	VARCHAR(200) NOT NULL,
	"table"	VARCHAR(200) NOT NULL,
	"field"	VARCHAR(200) NOT NULL,
	"type"	VARCHAR(200) NOT NULL,
	"comment"	VARCHAR(200),
	"pk"	BOOLEAN,
	"autoincrement"	BOOLEAN,
	"nullable"	BOOLEAN,
	"computed"	BOOLEAN,
	"default"	BOOLEAN,
	"fk"	BOOLEAN,
	"referred_table"	VARCHAR(200),
	"referred_column"	VARCHAR(200),
	"user_id"	INTEGER,
	"created_at"	DATETIME,
	"updated_at"	DATETIME,
	"excluded"	BOOLEAN,
	"field_order"	INTEGER,
	PRIMARY KEY("table_schema_id" AUTOINCREMENT),
	FOREIGN KEY("user_id") REFERENCES "users"("user_id")
);
CREATE TABLE IF NOT EXISTS task (
	task_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	task VARCHAR(100) NOT NULL, 
	task_desc TEXT, 
	starts_at DATETIME NOT NULL, 
	ends_at DATETIME, 
	calendar_id INTEGER, 
	calendar_color VARCHAR(50), 
	calendar_email VARCHAR(200), 
	task_status_id INTEGER, 
	task_status VARCHAR(50), 
	attach_task VARCHAR(200), 
	repeat BOOLEAN, 
	repeat_type_id INTEGER, 
	days_of_week VARCHAR(200), 
	repeat_start_date DATE, 
	repeat_start_time TIME, 
	repeat_end_date DATE, 
	repeat_end_time TIME, 
	attendees TEXT, 
	active BOOLEAN, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(calendar_id) REFERENCES calendar (calendar_id), 
	FOREIGN KEY(task_status_id) REFERENCES task_status (task_status_id), 
	FOREIGN KEY(repeat_type_id) REFERENCES repeat_type (repeat_type_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS task_status (
	task_status_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	task_status VARCHAR(10) NOT NULL, 
	excluded BOOLEAN
);
CREATE TABLE IF NOT EXISTS task_track (
	task_track_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	task_track VARCHAR(100) NOT NULL, 
	task_track_desc TEXT, 
	task_track_date DATETIME NOT NULL, 
	task_status_id INTEGER, 
	attach_task_track VARCHAR(200), 
	task_id INTEGER, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(task_status_id) REFERENCES task_status (task_status_id), 
	FOREIGN KEY(task_id) REFERENCES task (task_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS translate_table (
	transl_tbl_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	table_org_desc VARCHAR(200) NOT NULL, 
	table_transl_desc VARCHAR(200) NOT NULL, 
	"table" VARCHAR(200) NOT NULL, 
	db VARCHAR(200) NOT NULL, 
	lang VARCHAR(5) NOT NULL, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS translate_table_field (
	transl_tbl_field_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	field_org_desc VARCHAR(200) NOT NULL, 
	field_transl_desc VARCHAR(200) NOT NULL, 
	field VARCHAR(200) NOT NULL, 
	"table" VARCHAR(200) NOT NULL, 
	db VARCHAR(200) NOT NULL, 
	lang VARCHAR(5) NOT NULL, 
	user_id INTEGER, 
	app_id INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS user_log (
	user_log_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	user_id INTEGER, 
	action VARCHAR(200) NOT NULL, 
	req_ip VARCHAR(200), 
	req_at DATETIME, 
	req_data TEXT, 
	res_at DATETIME, 
	res_type VARCHAR(200), 
	res_msg VARCHAR(500), 
	res_data TEXT, 
	"table" VARCHAR(200), 
	db VARCHAR(200), 
	row_id INTEGER, 
	app_id INTEGER, 
	new_data TEXT, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(app_id) REFERENCES app (app_id)
);
CREATE TABLE IF NOT EXISTS user_role (
	user_role_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	user_id INTEGER, 
	role_id INTEGER, 
	active BOOLEAN, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(role_id) REFERENCES role (role_id)
);
CREATE TABLE IF NOT EXISTS users (
	user_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	username VARCHAR(50) NOT NULL, 
	first_name VARCHAR(50) NOT NULL, 
	last_name VARCHAR(50) NOT NULL, 
	email VARCHAR(50), 
	phone VARCHAR(50), 
	password VARCHAR(200) NOT NULL, 
	role_id INTEGER, 
	lang_id INTEGER, 
	timezone VARCHAR(50), 
	attach_profile_pic VARCHAR(200), 
	active BOOLEAN, 
	created_at DATETIME, 
	updated_at DATETIME, 
	excluded BOOLEAN, alter_pass_nxt_login boolean null, enable_2f_auth BOOLEAN NULL, nxt_code_2f_auth VARCHAR(200) NULL, code_2f_expires_at DATETIME NULL, 
	UNIQUE (username), 
	UNIQUE (email), 
	UNIQUE (phone), 
	FOREIGN KEY(role_id) REFERENCES role (role_id), 
	FOREIGN KEY(lang_id) REFERENCES lang (lang_id)
);
COMMIT;
