name: Build Test

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Prepare Dist Folder
        run: |
          mkdir -p dist
          mkdir -p dist/cs-windows-linking-amd64
          mkdir -p dist/cs-windows-linking-amd64/database
          cp ./LICENSE dist/cs-windows-linking-amd64
          cp ./README.md dist/cs-windows-linking-amd64
          cp -r ./static dist/cs-windows-linking-amd64
          cp -r ./locales dist/cs-windows-linking-amd64
          mkdir -p dist/cs-windows-linking-arm64
          mkdir -p dist/cs-windows-linking-arm64/database
          cp ./LICENSE dist/cs-windows-linking-arm64
          cp ./README.md dist/cs-windows-linking-arm64
          cp -r ./static dist/cs-windows-linking-arm64
          cp -r ./locales dist/cs-windows-linking-arm64
      # Step 2: Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      # Step 4: Install MinGW for Cross-Compilation
      - name: Install MinGW
        run: |
          choco install mingw -y
          Write-Host "MinGW installed for cross-compilation"

      # Step 5: Set Environment Variables
      - name: Set Environment Variables
        run: |
          echo "CGO_ENABLED=1" >> $env:GITHUB_ENV
          echo "CC=x86_64-w64-mingw32-gcc" >> $env:GITHUB_ENV

      # Step 7: Build the Application
      - name: Build Windows Binary
        run: |
          go build -o dist/cs-windows-linking-amd64/cs-windows-linking-amd64.exe ./cmd/api
          echo "GOARCH=arm64" >> $env:GITHUB_ENV
          go build -o dist/cs-windows-linking-arm64/cs-windows-linking-arm64.exe ./cmd/api
      #go build -tags=duckdb_use_lib -o dist/cs-windows-linking-amd64.exe ./cmd/api
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: dist/**  

  build-windows-linking:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Prepare Dist Folder
        run: |
          mkdir -p dist
          mkdir -p dist/cs-windows-linking-amd64
          mkdir -p dist/cs-windows-linking-amd64/database
          cp ./LICENSE dist/cs-windows-linking-amd64
          cp ./README.md dist/cs-windows-linking-amd64
          cp -r ./static dist/cs-windows-linking-amd64
          cp -r ./locales dist/cs-windows-linking-amd64
          mkdir -p dist/cs-windows-linking-arm64
          mkdir -p dist/cs-windows-linking-arm64/database
          cp ./LICENSE dist/cs-windows-linking-arm64
          cp ./README.md dist/cs-windows-linking-arm64
          cp -r ./static dist/cs-windows-linking-arm64
          cp -r ./locales dist/cs-windows-linking-arm64

      # Step 2: Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      # Step 3: Download DuckDB Precompiled Library
      - name: Download DuckDB Library
        run: |
          $version = "v1.3.1"
          $duckdb_url = "https://github.com/duckdb/duckdb/releases/download/$version/libduckdb-windows-amd64.zip"
          $destinationPath = "$(Get-Location)\duckdb"
          Invoke-WebRequest -Uri $duckdb_url -OutFile "duckdb.zip"
          Expand-Archive -Path "duckdb.zip" -DestinationPath $destinationPath
          Write-Host "DuckDB library extracted to $destinationPath"
          $duckdb_url = "https://github.com/duckdb/duckdb/releases/download/$version/libduckdb-windows-arm64.zip"
          $destinationPath = "$(Get-Location)\duckdbarm64"
          Invoke-WebRequest -Uri $duckdb_url -OutFile "duckdb.zip"
          Expand-Archive -Path "duckdb.zip" -DestinationPath $destinationPath
          Write-Host "DuckDB library extracted to $destinationPath"

      # Step 4: Install MinGW for Cross-Compilation
      - name: Install MinGW
        run: |
          choco install mingw -y
          Write-Host "MinGW installed for cross-compilation"

      # Step 5: Set Environment Variables
      - name: Set Environment Variables
        run: |
          echo "CGO_ENABLED=1" >> $env:GITHUB_ENV
          echo "CC=x86_64-w64-mingw32-gcc" >> $env:GITHUB_ENV
          echo "CGO_CFLAGS=-I$(Get-Location)\duckdb\" >> $env:GITHUB_ENV
          echo "CGO_LDFLAGS=-L$(Get-Location)\duckdb\ -lduckdb" >> $env:GITHUB_ENV

      # Step 6: Verify DuckDB Library
      - name: Verify DuckDB Library
        run: |
          $libPath = "$(Get-Location)\duckdb\"
          if (!(Test-Path "$libPath\duckdb.lib")) {
            Write-Error "duckdb.lib not found in $libPath"
          }
          Write-Host "duckdb.lib found in $libPath"

      # Step 7: Build the Application
      - name: Build Windows Binary
        run: |
          go build -o dist/cs-windows-linking-amd64/cs-windows-linking-amd64.exe ./cmd/api
          echo "CGO_ENABLED=1" >> $env:GITHUB_ENV
          echo "CC=x86_64-w64-mingw32-gcc" >> $env:GITHUB_ENV
          echo "CGO_CFLAGS=-I$(Get-Location)\duckdbarm64\" >> $env:GITHUB_ENV
          echo "CGO_LDFLAGS=-L$(Get-Location)\duckdbarm64\ -lduckdb" >> $env:GITHUB_ENV
          echo "GOARCH=arm64" >> $env:GITHUB_ENV
          go build -o dist/cs-windows-linking-arm64/cs-windows-linking-arm64.exe ./cmd/api
      #go build -tags=duckdb_use_lib -o dist/cs-windows-linking-amd64.exe ./cmd/api
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary-linking
          path: dist/**
