name: Build Test

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc g++ unixodbc unixodbc-dev

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
        
      - name: Prepare Dist Folder
        run: |
          mkdir -p dist
          mkdir -p dist/cs-linux-amd64
          mkdir -p dist/cs-linux-amd64/database
          cp ./LICENSE dist/cs-linux-amd64
          cp ./README.md dist/cs-linux-amd64
          cp -r ./static dist/cs-linux-amd64
          cp -r ./locales dist/cs-linux-amd64

      - name: Build Linux Binaries
        run: |
          CGO_ENABLED=1 go build -o dist/cs-linux-amd64/cs-linux-amd64 ./cmd/api

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: dist/**